#!/bin/sh

# verify $ARGS are venvs in output from `workon`

# loop
#   workon venv
#   pip freeze to tmp

# vimdiff tmps

# wait for return 
# delete tmps

# args in a list
echo $@

# requirements
#  virtuenvwrapper
#  vim
#  ~/bin created and added to $PATH

# install like this
# curl https://raw.github.com/bmcorser/venvdiff/master/venvdiff > ~/bin/venvdiff && chmod 0755 !#:3

# using temp files
# http://content.hccfl.edu/pollock/ShScript/TempFile.htm
