#!/bin/sh

# verify venvs

# loop
#   workon venv
#   pip freeze to tmp

# vimdiff tmps

# wait for return 
# delete tmps

echo $@

# install like this
# curl http://betterthangrep.com/ack-standalone > ~/bin/ack && chmod 0755 !#:3
